[Settings]
  ID = "d2b722a4-6f9d-4a8b-97a0-08c9c6221158"

[build]
  command = "yarn run build --log-level=1"
  publish = "dist/"

[build.environment]
  YARN_VERSION = "1.7.0"

[context.production.environment]
  HOST = "https://funding.inreachventures.com"
  API_HOST = "https://api.funding.inreachventures.com"
  SENTRY_DSN = "https://73fbb3a2ad3244d08f0bbfb15610c649@sentry.io/1228772"

[context.development.environment]
  HOST = "https://development.funding.inreachventures.com"
  API_HOST = "https://api-dev.funding.inreachventures.com"

[[redirect]]
  from = "https://funding.inreach.app/*"
  to = "https://funding.inreachventures.com/:splat"
  status = 301

[[redirects]]
  from = "/auth"
  to = "https://api.funding.inreachventures.com/auth?token=:token&redirect=:redirect"
  query = {redirect = ":redirect", token = ":token"}
  status = 302

[[redirects]]
  from = "/in"
  to = "https://api.funding.inreachventures.com/auth?token=:token&redirect=:redirect"
  query = {redirect = ":redirect", token = ":token"}
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
