[Settings]
  ID = "d2b722a4-6f9d-4a8b-97a0-08c9c6221158"

[build]
  command = "yarn run build --log-level=1"
  publish = "dist/"

[build.environment]
  YARN_VERSION = "1.7.0"

[context.production.environment]
  HOST = "https://funding.inreachventures.com"
  API_HOST = "https://api.funding.inreachventures.com"
  SENTRY_DSN = "https://73fbb3a2ad3244d08f0bbfb15610c649@sentry.io/1228772"

[context.development.environment]
  HOST = "https://development.funding.inreachventures.com"
  API_HOST = "https://api-dev.funding.inreachventures.com"

[[redirects]]
  from = "*"
  to = "https://getfunded.inreachventures.com"
  force = true
  status = 301

[[headers]]
  for = "/"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'none'; frame-src https://*.hotjar.com; media-src https://js.intercomcdn.com; script-src 'self' http://*.hotjar.com https://*.hotjar.com https://*.hotjar.com www.google-analytics.com https://app.intercom.io https://widget.intercom.io https://js.intercomcdn.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.hotjar.com http://*.hotjar.com https://www.google-analytics.com https://js.intercomcdn.com https://static.intercomassets.com https://downloads.intercomcdn.com https://uploads.intercomusercontent.com https://gifs.intercomcdn.com https://messenger-apps.intercom.io https://*.intercom-attachments.com; connect-src https://*.funding.inreachventures.com http://*.hotjar.com:* https://*.hotjar.com:* https://*.hotjar.io:* wss://*.hotjar.com https://sentry.io https://api.intercom.io https://api-iam.intercom.io https://api-ping.intercom.io https://nexus-websocket-a.intercom.io https://nexus-websocket-b.intercom.io https://nexus-long-poller-a.intercom.io https://nexus-long-poller-b.intercom.io wss://nexus-websocket-a.intercom.io wss://nexus-websocket-b.intercom.io https://uploads.intercomcdn.com https://uploads.intercomusercontent.com; child-src https://*.hotjar.com https://share.intercom.io https://intercom-sheets.com https://www.intercom-reporting.com https://www.youtube.com https://player.vimeo.com https://fast.wistia.net; font-src http://*.hotjar.com https://*.hotjar.com https://js.intercomcdn.com; form-action https://intercom.help https://api-iam.intercom.io;"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Referrer-Policy = "strict-origin"
    Content-Security-Policy = "default-src 'none'; frame-src https://*.hotjar.com; media-src https://js.intercomcdn.com; script-src 'self' http://*.hotjar.com https://*.hotjar.com https://*.hotjar.com www.google-analytics.com https://app.intercom.io https://widget.intercom.io https://js.intercomcdn.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.hotjar.com http://*.hotjar.com https://www.google-analytics.com https://js.intercomcdn.com https://static.intercomassets.com https://downloads.intercomcdn.com https://uploads.intercomusercontent.com https://gifs.intercomcdn.com https://messenger-apps.intercom.io https://*.intercom-attachments.com; connect-src https://*.funding.inreachventures.com http://*.hotjar.com:* https://*.hotjar.com:* https://*.hotjar.io:* wss://*.hotjar.com https://sentry.io https://api.intercom.io https://api-iam.intercom.io https://api-ping.intercom.io https://nexus-websocket-a.intercom.io https://nexus-websocket-b.intercom.io https://nexus-long-poller-a.intercom.io https://nexus-long-poller-b.intercom.io wss://nexus-websocket-a.intercom.io wss://nexus-websocket-b.intercom.io https://uploads.intercomcdn.com https://uploads.intercomusercontent.com; child-src https://*.hotjar.com https://share.intercom.io https://intercom-sheets.com https://www.intercom-reporting.com https://www.youtube.com https://player.vimeo.com https://fast.wistia.net; font-src http://*.hotjar.com https://*.hotjar.com https://js.intercomcdn.com; form-action https://intercom.help https://api-iam.intercom.io;"
