[Settings]
  ID = "d2b722a4-6f9d-4a8b-97a0-08c9c6221158"

[build]
  command = "yarn run build --log-level=1"
  publish = "dist/"

[build.environment]
  YARN_VERSION = "1.7.0"

[context.production.environment]
  HOST = "https://funding.inreachventures.com"
  API_HOST = "https://api.funding.inreachventures.com"
  SENTRY_DSN = "https://73fbb3a2ad3244d08f0bbfb15610c649@sentry.io/1228772"

[context.development.environment]
  HOST = "https://development.funding.inreachventures.com"
  API_HOST = "https://api-dev.funding.inreachventures.com"

[[redirects]]
  from = "https://funding.inreach.app/*"
  to = "https://funding.inreachventures.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "/auth"
  to = "https://api.funding.inreachventures.com/auth?token=:token&redirect=:redirect"
  query = {redirect = ":redirect", token = ":token"}
  status = 302

[[redirects]]
  from = "/auth"
  to = "https://api.funding.inreachventures.com/auth?token=:token"
  query = {redirect = "https://funding.inreachventures.com", token = ":token"}
  status = 302

[[redirects]]
  from = "/in"
  to = "https://api.funding.inreachventures.com/auth?token=:token&redirect=:redirect"
  query = {redirect = ":redirect", token = ":token"}
  status = 302

[[redirects]]
  from = "/in"
  to = "https://api.funding.inreachventures.com/auth?token=:token"
  query = {redirect = "https://funding.inreachventures.com", token = ":token"}
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'none'; script-src 'self' www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' https://www.google-analytics.com; connect-src https://*.funding.inreachventures.com https://sentry.io;"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Security-Policy = "default-src 'none'; script-src 'self' www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' https://www.google-analytics.com; connect-src https://*.funding.inreachventures.com https://sentry.io;"
    Referrer-Policy = "strict-origin"
